### ISSUE TITLE
Hello, is there any new example of the signature of the Monroe ring?

### ISSUE THREAD

**Issue by wangqi1996** [moneroexamples/ring-signatures#2]
Hello, is there any new example of the ring signature of the Monroe ?
Similar to this project
thanks

**Comment by moneroexamples** [comment]
Not really. What are you looking for specifically? Maybe other projects have what you can use. If you specify what you are after, I could maybe direct you there.

**Comment by wangqi1996** [comment]
My topic is to investigate the ring signature in Monroe.
Do you have any recommendations for this?

**Comment by moneroexamples** [comment]
Good start would be monero white paper. Then you can look at monero source code for implementation details.

**Comment by wangqi1996** [comment]
thanks~
